image: bnayatestim/root-cause-gitpod-demo-image:latest

tasks:
  - init: |
      # set -x

      if [[ -z "${RUN_PLAYWRIGHT_EXAMPLE}" ]]
      then
        cd with-jest-puppeteer
      else
        cd with-jest-playwright
      fi
      npm install --prefer-offline
      cd -

    command: source gitpodCommand.sh

ports:
  - port: 9876
    onOpen: open-browser
