image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # set -x

      if [[ -z "${RUN_PLAYWRIGHT_EXAMPLE}" ]]
      then
        cd with-jest-puppeteer
      else
        cd with-jest-playwright
      fi
      npm install
      cd -

    command: ./gitpodCommand.sh

ports:
  - port: 9876
    onOpen: open-browser
