image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      set -x
      if [ -n $RUN_PLAYWRIGHT_EXAMPLE ]
      then
        cd with-jest-playwright
      else
        cd with-jest-puppeteer
      fi
      npm install
      cd -

    command: |
      set -x

      if [ -n $RUN_PLAYWRIGHT_EXAMPLE ]
      then
        cd with-jest-playwright
      else
        cd with-jest-puppeteer
      fi
      npx jest
      npx rc ls
      npx rc ls --simple | xargs npx rc show

ports:
  - port: 9876
    onOpen: open-browser
